<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PiSharp.Ai</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Providers\Data\*.json" LogicalName="PiSharp.Ai.Providers.Data.%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PiSharp.Ai.Tests" />
  </ItemGroup>

</Project>
