<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Iris.Ai</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Providers\Data\*.json" LogicalName="Iris.Ai.Providers.Data.%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Iris.Ai.Tests" />
  </ItemGroup>

</Project>
