<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Iris.Agent</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Iris.Ai\Iris.Ai.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Iris.Agent.Tests" />
  </ItemGroup>

</Project>
